export const SEO_KEYWORDS = [
  'Frontend',
  'Design',
  'Engineering',
  'Design Engineer',
  'User Interface',
  'User Interface Designer',
  'User Interface Engineer',
  'User Interface Design Engineer',
  'UI',
  'UI Designer',
  'UI Engineer',
  'UI Design Engineer',
  'UI components',
  'User experience',
  'UX',
  'UX Designer',
  'UX Engineer',
  'UX Design Engineer',
  'Design Systems',
  'Front-end Development',
  'Prototyping',
  'Interaction Design',
  'Motion Design',
  'Creative Coding',
  'Accessibility',
  'Next.js',
  'React',
  'TypeScript',
  'Figma'
];
