export { default as FigmaIcon } from './figma-icon';
export { default as WebstormIcon } from './webstorm-icon';
export { default as GithubIcon } from './github-icon';
export { default as GitlabIcon } from './gitlab-icon';
export { default as ShopwareIcon } from './shopware-icon';
export { default as StoryblokIcon } from './storyblok-icon';
export { default as MiroIcon } from './miro-icon';
export { default as MarkdownIcon } from './markdown-icon';
export { default as ReactIcon } from './react-icon';
export { default as NextJsIcon } from './next-js-icon';
export { default as HTMLIcon } from './html-icon';
export { default as CSSIcon } from './css-icon';
export { default as TailwindCssIcon } from './tailwind-css-icon';
export { default as MotionIcon } from './motion-icon';
export { default as XingIcon } from './xing-icon';
export { default as LinkedinIcon } from './linkedin-icon';
export { default as TypescriptIcon } from './typescript-icon';
export { default as JavaScriptIcon } from './javascript-icon';
export { default as NotesIcon } from './notes-icon';
export { default as CraftIcon } from './craft-icon';
export { default as ChromeLogo } from './chrome-logo';
export { default as FirefoxLogo } from './firefox-logo';
export { default as SafariLogo } from './safari-logo';
export { default as SlackLogo } from './slack-logo';
export { default as TeamsLogo } from './teams-logo';

export const defaultIconSize = 'size-8';
